In [1]:
import pandas as pd

df = pd.read_csv("Global_Operative_Dataset.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [2]:
df.head(10)

,name,gender,status,affiliation,faction,role,weapon,emotion,mission_count,location,rank,loyalty
0,Michael Carter 1,Female,Inactive,Continental,Handler,Operative,Pistol,Neutral,189,London,Novice,Absolute
1,Ryan Carter 2,Male,Inactive,Continental,Contractor,Enforcer,Pistol,Determined,50,London,Elite,Medium
2,Benjamin Hunter 3,Female,Active,Continental,Crime Syndicate,Bodyguard,Rifle,Angry,55,Osaka,Novice,Low
3,Oliver Walker 4,Female,Missing,Underworld,Security,Hitman,Unarmed,Fearful,137,Rome,Elite,Low
4,Joseph Brooks 5,Female,Inactive,Independent,Assassin,Operative,Knife,Focused,20,Berlin,Novice,Absolute
5,William Ward 6,Female,Inactive,High Table,Security,Tracker,Unarmed,Focused,179,Rome,Master,Medium
6,Joseph Hayes 7,Male,Deceased,Ruska Roma,Security,Operative,Unarmed,Determined,56,Osaka,Novice,Medium
7,Ryan Turner 8,Female,Missing,Independent,Handler,Enforcer,Unarmed,Focused,54,Casablanca,Elite,Absolute
8,James Foster 9,Male,Inactive,Underworld,Contractor,Bodyguard,Unarmed,Determined,109,Marrakesh,Elite,High
9,Lucas Bennett 10,Female,Active,Independent,Assassin,Tracker,Unarmed,Angry,202,Prague,Master,Low

In [3]:
df.tail(10)

,name,gender,status,affiliation,faction,role,weapon,emotion,mission_count,location,rank,loyalty
99990,Lucas Hunter 99991,Female,Missing,High Table,Security,Tracker,Pistol,Neutral,158,Berlin,Novice,Absolute
99991,William Hunter 99992,Male,Missing,Independent,Contractor,Tracker,Rifle,Neutral,74,Casablanca,Elite,Medium
99992,David Griffin 99993,Male,Active,Underworld,Assassin,Bodyguard,Pistol,Focused,49,Osaka,Elite,Absolute
99993,David Walker 99994,Male,Missing,Independent,Assassin,Bodyguard,Shotgun,Determined,241,London,Master,Absolute
99994,Leo Walker 99995,Female,Active,Underworld,Crime Syndicate,Hitman,Knife,Neutral,131,Marrakesh,Senior Agent,Absolute
99995,Jack Griffin 99996,Female,Active,Continental,Contractor,Tracker,Pistol,Focused,226,Paris,Elite,Absolute
99996,Benjamin Collins 99997,Female,Deceased,Continental,Crime Syndicate,Operative,Shotgun,Fearful,220,Casablanca,Elite,High
99997,Thomas Reed 99998,Female,Deceased,High Table,Assassin,Operative,Unarmed,Determined,186,London,Elite,Medium
99998,James Foster 99999,Male,Missing,Continental,Crime Syndicate,Tracker,Rifle,Fearful,184,Paris,Master,Absolute
99999,Samuel Morgan 100000,Male,Missing,High Table,Security,Bodyguard,Rifle,Focused,73,Casablanca,Master,High

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 100000
Columns: 12

In [5]:
print(df.columns)

Index(['name', 'gender', 'status', 'affiliation', 'faction', 'role', 'weapon',
       'emotion', 'mission_count', 'location', 'rank', 'loyalty'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   name           100000 non-null  object
 1   gender         100000 non-null  object
 2   status         100000 non-null  object
 3   affiliation    100000 non-null  object
 4   faction        100000 non-null  object
 5   role           100000 non-null  object
 6   weapon         100000 non-null  object
 7   emotion        100000 non-null  object
 8   mission_count  100000 non-null  int64
 9   location       100000 non-null  object
 10  rank           100000 non-null  object
 11  loyalty        100000 non-null  object
dtypes: int64(1), object(11)
memory usage: 9.2+ MB

In [7]:
print(df.isnull().sum())

name             0
gender           0
status           0
affiliation      0
faction          0
role             0
weapon           0
emotion          0
mission_count    0
location         0
rank             0
loyalty          0
dtype: int64

In [8]:
print("Duplicate records:", df.duplicated().sum())

Duplicate records: 0

In [9]:
print(df["gender"].value_counts())

gender
Male      50021
Female    49979
Name: count, dtype: int64

In [10]:
print(df["status"].value_counts())

status
Active      25131
Missing     25104
Inactive    24936
Deceased    24829
Name: count, dtype: int64

In [11]:
print(df["location"].value_counts())

location
London        10134
Casablanca    10120
Osaka         10078
Rome          10055
Prague        10005
Tokyo          9961
Marrakesh      9926
Paris          9919
Berlin         9918
New York       9884
Name: count, dtype: int64

In [12]:
print(df["rank"].value_counts())

rank
Senior Agent    20272
Master          20257
Novice          19995
Agent           19760
Elite           19716
Name: count, dtype: int64

In [13]:
print(df["weapon"].value_counts())

weapon
Unarmed    16880
Knife      16717
Sword      16662
Pistol     16616
Rifle      16587
Shotgun    16538
Name: count, dtype: int64

In [14]:
print("Average missions:", df["mission_count"].mean())

Average missions: 124.98727

In [15]:
print("Maximum missions:", df["mission_count"].max())

Maximum missions: 250

In [16]:
print("Minimum missions:", df["mission_count"].min())

Minimum missions: 0

In [17]:
df.sort_values("mission_count", ascending=False).head(10)

,name,gender,status,affiliation,faction,role,weapon,emotion,mission_count,location,rank,loyalty
8945,Michael Brooks 8946,Female,Deceased,Ruska Roma,Assassin,Hitman,Pistol,Angry,250,Paris,Senior Agent,Low
8947,Daniel Bailey 8948,Male,Inactive,Underworld,Security,Enforcer,Sword,Focused,250,Paris,Elite,Low
37358,Alex Morgan 37359,Female,Missing,Ruska Roma,Contractor,Operative,Shotgun,Calm,250,Berlin,Novice,Low
5971,Samuel Murphy 5972,Female,Active,Underworld,Contractor,Tracker,Sword,Fearful,250,New York,Elite,Low
37721,William Hayes 37722,Male,Inactive,Ruska Roma,Assassin,Hitman,Unarmed,Calm,250,New York,Novice,Medium
9876,Leo Turner 9877,Male,Missing,Continental,Handler,Tracker,Rifle,Focused,250,Marrakesh,Elite,Medium
9751,Andrew Bailey 9752,Male,Missing,Underworld,Security,Hitman,Knife,Focused,250,Rome,Agent,Low
9707,Lucas Mitchell 9708,Female,Missing,Ruska Roma,Handler,Bodyguard,Shotgun,Fearful,250,Tokyo,Novice,Low
99316,Ethan Cooper 99317,Female,Inactive,Ruska Roma,Assassin,Bodyguard,Shotgun,Determined,250,Osaka,Senior Agent,Medium
9380,David Morgan 9381,Female,Active,Ruska Roma,Handler,Enforcer,Sword,Focused,250,Osaka,Senior Agent,Low

In [18]:
name = input("Enter operative name: ")

result = df[
    df["name"].str.contains(name, case=False, na=False)
]

display(result)

Enter operative name: mission codex

Empty DataFrame
Columns: [name, gender, status, affiliation, faction, role, weapon, emotion, mission_count, location, rank, loyalty]
Index: []

In [19]:
result = df[df["mission_count"] > 100]

print("Number of operatives:", len(result))
display(result.head(20))

Number of operatives: 59633

,name,gender,status,affiliation,faction,role,weapon,emotion,mission_count,location,rank,loyalty
0,Michael Carter 1,Female,Inactive,Continental,Handler,Operative,Pistol,Neutral,189,London,Novice,Absolute
3,Oliver Walker 4,Female,Missing,Underworld,Security,Hitman,Unarmed,Fearful,137,Rome,Elite,Low
5,William Ward 6,Female,Inactive,High Table,Security,Tracker,Unarmed,Focused,179,Rome,Master,Medium
8,James Foster 9,Male,Inactive,Underworld,Contractor,Bodyguard,Unarmed,Determined,109,Marrakesh,Elite,High
9,Lucas Bennett 10,Female,Active,Independent,Assassin,Tracker,Unarmed,Angry,202,Prague,Master,Low
10,Oliver Cooper 11,Female,Missing,Underworld,Assassin,Operative,Unarmed,Calm,174,London,Senior Agent,High
11,Michael Brooks 12,Female,Inactive,Ruska Roma,Assassin,Operative,Unarmed,Focused,248,London,Agent,Low
12,Henry Russell 13,Male,Inactive,High Table,Handler,Enforcer,Shotgun,Calm,153,Osaka,Elite,Low
13,Michael Mitchell 14,Female,Inactive,Independent,Handler,Enforcer,Pistol,Calm,187,Casablanca,Novice,Medium
14,James Bailey 15,Male,Missing,Underworld,Contractor,Manager,Knife,Determined,193,Berlin,Senior Agent,Absolute
15,Leo Ward 16,Female,Active,Continental,Handler,Hitman,Rifle,Calm,150,London,Agent,Medium
17,Joseph Bennett 18,Female,Inactive,Ruska Roma,Crime Syndicate,Tracker,Pistol,Calm,168,Prague,Senior Agent,Absolute
23,Lucas Cooper 24,Male,Inactive,Underworld,Contractor,Hitman,Shotgun,Calm,107,Marrakesh,Master,High
25,Alex Ward 26,Male,Active,Underworld,Handler,Enforcer,Rifle,Angry,238,Osaka,Novice,Medium
31,Andrew Bennett 32,Male,Inactive,Continental,Crime Syndicate,Hitman,Knife,Neutral,236,Osaka,Elite,Medium
33,Alex Parker 34,Female,Missing,High Table,Assassin,Bodyguard,Rifle,Neutral,130,Prague,Master,High
34,Alex Walker 35,Female,Inactive,Underworld,Security,Hitman,Pistol,Determined,111,Osaka,Senior Agent,Absolute
35,Andrew Russell 36,Male,Deceased,Underworld,Handler,Bodyguard,Pistol,Neutral,111,New York,Master,Medium
36,Leo Murphy 37,Male,Missing,Underworld,Security,Operative,Pistol,Neutral,230,Tokyo,Master,High
37,Thomas Turner 38,Female,Missing,Underworld,Handler,Tracker,Sword,Neutral,240,Prague,Agent,High

In [20]:
result = df.groupby("rank")["mission_count"].mean()

print(result)

rank
Agent           125.911083
Elite           124.467793
Master          125.469072
Novice          124.768992
Senior Agent    124.325868
Name: mission_count, dtype: float64